name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Desarrollo Surge
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
              python-version: '3.x'
              architecture: 'x64'
    - run: pip install html5validator
    - run: html5validator --root _build/
    - name: Install surge and fire deployment
      uses: actions/setup-node@v1
      with:
          node-version: 8
    - run: npm install -g surge
    - run: surge ./_build/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      
